# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test_FS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.4.0'
  pod 'Kingfisher', '~> 5.15.7'
  pod 'SnapKit', '~> 5.0.1'

end
